### ISSUE TITLE
Prow broken when deploying upstream latest

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#106]
See https://github.com/GoogleCloudPlatform/oss-test-infra/pull/105

I think also plank is missing rbac rules... maybe other thigns.

Need to investigate further

**Comment by fejta** [comment]
/assign @BenTheElder 

Fixed maybe?

**Comment by BenTheElder** [comment]
:eyes:

**Comment by fejta** [comment]
We've now bumped
/close
