### ISSUE TITLE
Cert-manager version is not supported by letsencrypt.

### ISSUE THREAD

**Issue by cjwagner** [GoogleCloudPlatform/oss-test-infra#142]
Same problem as here: https://github.com/kubernetes/test-infra/issues/14944

File for this instance: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/cluster/cert-manager.yaml

/kind oncall-hotlist
cc @Katharine

**Comment by Katharine** [comment]
For the record:

The plan is to move over to GKE Managed Certs. This is going to involve some downtime (~20 minutes) as we perform the transition. We have until January 15th to get this done.

I'll put up the PR that does the magic soon.

/assign

**Comment by fejta** [comment]
Show me the magic!

**Comment by cjwagner** [comment]
Bump. Just got an email reminder that the cert expires on January 17th.

**Comment by Katharine** [comment]
Fixed by #199
