### ISSUE TITLE
Problem on updating the external secret for s390x-knative

### ISSUE THREAD

**Issue by BbolroC** [GoogleCloudPlatform/oss-test-infra#1441]
It looks the external secrets for the following have not been properly updated since 7:00 UTC on the 29th of Jan. 

https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/cluster/build/600-kubernetes_external_secrets.yaml

The role `secretmanager.viewer` and `secretmanager.secretAccessor` are granted to the service account `serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com`. 

The configuration has not been changed for a couple of months. It is confirmed that the update on the secret worked until 6:00 UTC.

Could someone from the cluster admins have a look at what went wrong around this?

**Comment by BbolroC** [comment]
@chaodaiG Hi, could you have a look at this if you have time? Thank you. :wink: So many of our prow jobs go red due to this issue atm: https://prow.knative.dev/?job=*s390x*

**Comment by chaodaiG** [comment]
@cjwagner , is this possibly related to the upgrade of KES?

**Comment by cjwagner** [comment]
> @cjwagner , is this possibly related to the upgrade of KES?

I don't think so, the timing doesn't match up. K8s reports the pod as "Ready", but it hasn't emitted any new logs since 2022-01-29T07:05:53.100Z. I'll restart the pod.

**Comment by cjwagner** [comment]
Logs indicate this is working again.
I'm not sure what caused this or how to prevent it from happening again. I suggest we wait to see if this ever happens again before resorting to replacing KES (since it is EOL we can't get any new fixes).
