### ISSUE TITLE
Add support for testgrid annotations on prowjobs

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#152]
Can we get your utility set up on this repo to a) automatically create/update a testgrid.yaml based on the annotations on prowjobs in this repo and b) create kubernetes/test-infra PRs to get this added to testgrid.k8s.io?

/assign @chases2

**Comment by chases2** [comment]
Yes. I plan to start this once the Transfigure image is working as intended for Istio.

Then, I can create docs for an example Prow Job and use it here.

**Comment by chases2** [comment]
Tests are currently running, but aren't passing. See https://github.com/GoogleCloudPlatform/oss-test-infra/pull/189

**Comment by chases2** [comment]
Tests are now passing. See #193
