### ISSUE TITLE
Prow Jobs stuck in triggered state

### ISSUE THREAD

**Issue by chases2** [GoogleCloudPlatform/oss-test-infra#159]
/cc @fejta @BenTheElder 

All of the Prow Jobs on the gflocks instance of Prow have been stuck in "triggered" state since Nov 7th. https://prow.gflocks.com/

Rerunning jobs seems to only get them _also_ stuck in that state.

**Comment by BenTheElder** [comment]
looks like
- we have a build cluster with bad certs (agones)
- we have missing RBAC to list prowjobs in at least some components
- we have missing RBAC to do leader election in sinker

Not sure what else, but none of this should be new. I did not mutate this cluster yesterday and I do not remember being informed of any changes. :|

**Comment by BenTheElder** [comment]
prow/cluster has not changed in 7 days. I'm not sure what introduced this yet though..

**Comment by hopkiw** [comment]
Our legacy prow cluster (that we are migrating away from in favor of this OSS cluster) also had a bizarre change in behavior with stuck jobs that didn't seem related to any recent change. Would be willing to share logs or give inspection access if it would be helpful.

**Comment by BenTheElder** [comment]
I don't think that's related, we diagnosed this particular bug to a bad build cluster credential that caused plank to lock up.

**Comment by BenTheElder** [comment]
Please file an issue with test-infra / prow upstream. This issue is for tracking issues with the cluster the current oncall maintains, as opposed to general prow issues that OWNERS of components should handle.

**Comment by chases2** [comment]
The Prow cluster is now processing jobs
