### ISSUE TITLE
github oauth should be against the robot account, not a human

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/oss-test-infra#163]
![image](https://user-images.githubusercontent.com/917931/68520286-3b5d6280-024b-11ea-85ae-19a3f9f80771.png)
/assign @clarketm

**Comment by clarketm** [comment]
I sent a transfer request 2 months ago to `GoogleCloudPlatform` as suggested to me by the team at some point.
![image](https://user-images.githubusercontent.com/9957358/68520325-89726600-024b-11ea-804e-3833da9cbaae.png)

It was not accepted, so I will sent to bot instead. Someone with permission still needs to accept:
![image](https://user-images.githubusercontent.com/9957358/68520369-df470e00-024b-11ea-9a27-34c95f97ad9a.png)

/assign @BenTheElder

**Comment by BenTheElder** [comment]
you should have access to the account in [internal credential store] ?

**Comment by clarketm** [comment]
> you should have access to the account in [internal credential store] ?

If that is the case, then I will find the creds, login, then accept the transfer.

**Comment by BenTheElder** [comment]
I'm logged in but haven't foudn the transfer request just yet.

**Comment by clarketm** [comment]
/assign

Transfer complete.

**Comment by BenTheElder** [comment]
thanks!
