### ISSUE TITLE
unable to rerun jobs

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/oss-test-infra#164]
we return a 200 `You don't have permission to rerun that job` when I click rerun.

**Comment by clarketm** [comment]
Are you a member of [`@GoogleCloudPlatform/googlers`](https://github.com/orgs/GoogleCloudPlatform/teams/googlers)? Rerun is currently configured to authorize any member of this particular GitHub team.

https://github.com/GoogleCloudPlatform/oss-test-infra/blob/e73191c4bc0b79ef1d8fcb61113e67362fb2bd95/prow/config.yaml#L88-L90

**Comment by BenTheElder** [comment]
I am not, sent a request to join. This team is surprising as it's not listed in go/github.
I am a member of the Orgs.

**Comment by clarketm** [comment]
@BenTheElder

> I am not, sent a request to join. This team is surprising as it's not listed in go/github.

It is surprising. I personally do not recall *explicitly* needing to join this group, maybe new member are now auto-enrolled when they join the `GoogleCloudPlatform` org. 

> I am a member of the Orgs.

I recently added support for using GitHub orgs to authorize rerun: https://github.com/kubernetes/test-infra/pull/15393. Before this we needed either a user-list or GitHub team. It might make more sense now to switch this to the `GoogleCloudPlatform` org.

**Comment by BenTheElder** [comment]
> It is surprising. 🤔 I personally do not recall explicitly needing to join this group, maybe new member are now auto-enrolled when they join the GoogleCloudPlatform org.

hmm yeah that might be it.

> I recently added support for using GitHub orgs to authorize rerun: kubernetes/test-infra#15393. Before this we needed either a user-list or GitHub team. It might make more sense now to switch this to the GoogleCloudPlatform org.


SGTM 👍

**Comment by BenTheElder** [comment]
so i am a member now and it seems to be working, a bit slower than I remember but 🤷‍♂

**Comment by clarketm** [comment]
> so i am a member now and it seems to be working, a bit slower than I remember but 🤷‍♂

Not sure on the cause of the slowness 🤷‍♂
