### ISSUE TITLE
Add KFP backend presubmit test to prow config at prow/prowjobs/kubeflow/kubeflow-presubmits.yaml

### ISSUE THREAD

**Issue by jingzhang36** [GoogleCloudPlatform/oss-test-infra#187]

**Comment by jlewi** [comment]
@jingzhang36 you might want to file an issue in kubeflow/pipelines so that it gets tracked as part of the KFP work items.

**Comment by jingzhang36** [comment]
@jlewi do you know the ETA of these two PRs https://github.com/GoogleCloudPlatform/oss-test-infra/pull/93 and https://github.com/GoogleCloudPlatform/oss-test-infra/pull/177? If they are not planned to be merge soon, I'll probably still add Prow tests of KFP backend to the old place.

**Comment by jingzhang36** [comment]
Close this one to open in kubeflow/pipelines repo
