### ISSUE TITLE
Cannot assign issues to GCP members

### ISSUE THREAD

**Issue by krzyzacy** [GoogleCloudPlatform/oss-test-infra#20]
ref https://github.com/GoogleCloudPlatform/oss-test-infra/pull/19#issuecomment-488851272

**Comment by krzyzacy** [comment]
testing

/assign rofuentes hopkiw

**Comment by hopkiw** [comment]
:+1:

**Comment by krzyzacy** [comment]
(Added https://github.com/orgs/GoogleCloudPlatform/teams/compute-image-tools-admin as repo writer)
