### ISSUE TITLE
Tide does not reporting queries?

### ISSUE THREAD

**Issue by krzyzacy** [GoogleCloudPlatform/oss-test-infra#22]
https://prow.gflocks.com/tide is pretty blank, wonder if some config was missing? (reported by @hopkiw)

cc @cjwagner

**Comment by cjwagner** [comment]
Deck isn't configured to fetch data from Tide. (Notice that there is no "Tide" or "Tide History" section in the menu bar.)
This flag must be specified:
https://github.com/kubernetes/test-infra/blob/7840ca27e11b0e6272c470a5e0afccaedc926e68/prow/cmd/deck/main.go#L120
Similarly, Deck isn't configured to fetch plugin help data from hook.
We should probably add the `--tide-url`, `--hook-url`, and `--redirect-http-to` flags like the prow.k8s.io deployment has:
https://github.com/kubernetes/test-infra/blob/7840ca27e11b0e6272c470a5e0afccaedc926e68/prow/cluster/deck_deployment.yaml#L45-L47

**Comment by krzyzacy** [comment]
https://prow.gflocks.com/tide and https://prow.gflocks.com/tide-history works now :-) thanks @cjwagner !
