### ISSUE TITLE
Enable endpoint for cherrypicker plugin

### ISSUE THREAD

**Issue by andreyvelich** [GoogleCloudPlatform/oss-test-infra#2343]
Kubeflow community would like to [use cherrypicker Prow plugin](https://prow.k8s.io/command-help#cherrypick), similar to other Kubernetes projects: https://github.com/kubernetes/test-infra/blob/ab0aea453361484ad834f42c7cb633f5f74a3535/config/prow/plugins.yaml#L1826

According to the @cjwagner's comment currently this Prow instance doesn't have this service deployed: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2331#discussion_r1710130826

It would be nice to enable it.

cc @zijianjoy @chensun @james-jwu @chaodaiG @chases2 @cjwagner @fejta @michelle192837 @mpherman2 @thesuperzapper

**Comment by cjwagner** [comment]
I looked into this a bit. We need to parallel this issue: https://github.com/kubernetes/test-infra/issues/23469
I think we can reuse the https://github.com/google-oss-robot account that creates our autobump PRs ([example](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2334)). I'm not certain that the access token we have in our cluster will have all appropriate scopes, but I think it probably does given that it creates bump PRs. It is possible it is missing permissions to create new forks though.
I'll come back to give this a try when I have a bit more time.
/assign

**Comment by andreyvelich** [comment]
Thanks a lot for your time @cjwagner!

**Comment by cjwagner** [comment]
@andreyvelich This is deployed now. Please give it a try and let me know if it works!
There are some brief usage instructions on the [plugin help](https://oss.gprow.dev/plugins?repo=kubeflow%2Fkubeflow) and [command help](https://oss.gprow.dev/command-help#cherrypick) pages (they may take a bit to load).

**Comment by andreyvelich** [comment]
Thank you so much for doing this @cjwagner!
We will try this out once we need to cherry-pick some PRs.
cc @terrytangyuan @tenzen-y @thesuperzapper @juliusvonkohout @rimolive
