### ISSUE TITLE
testgrid config check failing for esp-v2

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/oss-test-infra#266]
https://prow.gflocks.com/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/259/pull-oss-test-infra-check-testgrid-config/1227020925258436608

/assign @TAOXUY 
/kind bug

**Comment by BenTheElder** [comment]
@michelle192837 do we want this check to be blocking?

**Comment by chases2** [comment]
I think we do want this check to block.
/assign

**Comment by chases2** [comment]
#259 is now passing this test. This should unblock you from merging.

**Comment by BenTheElder** [comment]
thanks!
