### ISSUE TITLE
pull-oss-test-infra-check-testgrid-config failed but passed

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#273]
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/270 shows X

https://prow.gflocks.com/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/270/pull-oss-test-infra-check-testgrid-config/1228047829478412290 shows green

https://prow.gflocks.com/prowjob?prowjob=488e4009-4e9c-11ea-86af-b23cf998d5f2 shows job failed

/assign @chases2 

What is going on here?

**Comment by chases2** [comment]
It looks like #270 merged. I still want to investigate which image (before or after https://github.com/kubernetes/test-infra/pull/16286) caused this issue.
