### ISSUE TITLE
"Rerun" Button on Deck redirects to old URL

### ISSUE THREAD

**Issue by chases2** [GoogleCloudPlatform/oss-test-infra#322]
When I click on the "rerun" button on a Prow job in Deck, I get redirected to https://prow.gflocks.com/github-login/redirect, which results in a Domain Not Found error. The job does not rerun.

Rerun needs to be reconfigured _somewhere_, but I don't know exactly where.

**Comment by chaodaiG** [comment]
This was fixed, the `glocks` domain is unused any more
