### ISSUE TITLE
Update build cluster instructions

### ISSUE THREAD

**Issue by michelle192837** [GoogleCloudPlatform/oss-test-infra#400]
Procedure for making a build cluster (mostly the command for updating the secret) changed slightly, so we need to update it accordingly.

The main differences:
* merge_kubernetes_secret.py is not in this repo (either need to copy it here or reference the script from test-infra)
* printed command from create_build_cluster.sh needs updated flags (--source-key and --dest-key, not --secret-key)
* command needs to note instructions for versioning the secret...
* ...and to update use of the --kubeconfig flag in the repo

Optionally:
* Would be nice if the script can intelligently version a key (i.e. find the most-recent key by date, and merge into a new key for today's date).

/assign @cjwagner

**Comment by cjwagner** [comment]
All the points have been addressed.
/close
