### ISSUE TITLE
Testgrid not updated with new jobs

### ISSUE THREAD

**Issue by nareddyt** [GoogleCloudPlatform/oss-test-infra#448]
ESPv2 has two testgrid dashboards:
- Presubmits: https://testgrid.k8s.io/googleoss-esp-v2-presubmit
- Periodics: https://testgrid.k8s.io/googleoss-esp-v2-periodic

We recently submitted PRs #446 and #447 last week with the proper testgrid annotations. But we don't see those jobs on our dashboards.

Example missing job:
- Testgrid name: `e2e-gcloud-build-image`
- Dashboards: Both presubmit and periodic

How long does it take for the jobs to be synced to testgrid? Or is it a manual process that I can do?

**Comment by nareddyt** [comment]
Assigning to @chases2 as he's helped with testgrid in the past. Feel free to re-assign if needed.

/assign @chases2

**Comment by nareddyt** [comment]
Friendly ping

**Comment by chases2** [comment]
It looks like the PR that Transfigure generated hasn't been approved yet. Your changes may be there:
https://github.com/kubernetes/test-infra/pull/18364

**Comment by nareddyt** [comment]
Thanks, I know where to look now for updates!
