### ISSUE TITLE
One Knative Prow job is always interrupted in 30mins

### ISSUE THREAD

**Issue by chizhg** [GoogleCloudPlatform/oss-test-infra#620]
The Prow job (https://prow.knative.dev/?job=ci-knative-test-infra-branchprotector) run by Knative Prow is always interrupted after running for ~30 mins.  Not sure why it only happens to this job, but I'm suspecting https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/config.yaml#L133 might be the reason.

**Comment by chaodaiG** [comment]
This looks very possible, but it's strange that sinker thinks the pod was terminated

**Comment by chizhg** [comment]
The issue has been root caused and fixed by Peter.
