### ISSUE TITLE
pull-knative-prow-config-validate Failing because "couldn't find remote ref master"

### ISSUE THREAD

**Issue by mpherman2** [GoogleCloudPlatform/oss-test-infra#730]
https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/723/pull-knative-prow-config-validate/1369018977103122432

**Comment by chases2** [comment]
Currently blocking https://github.com/GoogleCloudPlatform/oss-test-infra/pull/723
