### ISSUE TITLE
Problem on updating the external secret for knative

### ISSUE THREAD

**Issue by BbolroC** [GoogleCloudPlatform/oss-test-infra#879]
Since this Thursday (27th of May), it does not look that the secret value has been updated by the [external secret](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/cluster/build/600-kubernetes_external_secrets.yaml) when the corresponding secret on the gcp secret manager was changed. 

The log for the job `ci-knative-eventing-s390x-e2e-tests` has been showing the following error message:

```
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

On 28th, the value on the gcp secret manager was updated to a IP address (instead of the kubeconfig data), which is expected to cause the following error:

```
error: error loading config file "/root/.kube/config": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

But the error message on 29th is not changed (see the [log](https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-eventing-s390x-e2e-tests/1398549867231449088)).

It would be grateful if someone from the maintainers could confirm this doubt.

**Comment by BbolroC** [comment]
@chaodaiG @chizhg could you look into this issue if you have time? The error message still shows the following:

```
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

even if the value for `kubeconfig` is an ip address. Thanks.

**Comment by chaodaiG** [comment]
cluster log shows:
```
Permission 'secretmanager.versions.access' denied for resource 'projects/s390x-knative/secrets/kubeconfig/versions/latest' (or it may not exist).",
```

This error can also be found by searching for `s390x-cluster1` in cloud logging https://cloudlogging.app.goo.gl/XrstYdw9dVopwbpF6

**Comment by BbolroC** [comment]
Thank you very much. :wink: The cause for the problem is figured out.
