### ISSUE TITLE
secrets-store-csi-driver-provider-gcp is missing

### ISSUE THREAD

**Issue by tam7t** [GoogleCloudPlatform/oss-test-infra#971]
We have periodic tests scheduled here:
https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml

and had them previously viewable at:
https://oss-prow.knative.dev/?repo=GoogleCloudPlatform%2Fsecrets-store-csi-driver-provider-gcp&type=periodic

But https://oss-prow.knative.dev/ no longer includes the `secrets-store-csi-driver-provider-gcp` repo

**Comment by chaodaiG** [comment]
According to testgrid https://testgrid.k8s.io/googleoss-secrets-store-csi-driver-provider-gcp#periodic, the job `prow-e2e-tests-periodic` does run every day

And prow displays it https://oss-prow.knative.dev/?job=prow-e2e-tests-periodic, but not when grouped by repo https://oss-prow.knative.dev/?repo=GoogleCloudPlatform%2secrets-store-csi-driver-provider-gcp

seems like a bug in deck

**Comment by chaodaiG** [comment]
secrets-store-csi-driver-provider-gcp repo is not a user of prow any more

/close
